version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      # Uncomment these for production
      # - N8N_ENCRYPTION_KEY=your-secret-key
      # - NODE_ENV=production
      # Database configuration (uncomment to use PostgreSQL instead of SQLite)
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n
    volumes:
      - n8n_data:/home/node/.n8n
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Uncomment to add PostgreSQL database
  # postgres:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n
  #     - POSTGRES_DB=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U n8n"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  n8n_data:
  # postgres_data: